name: CI-WORKFLOW

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  buil-test:
    runs-on: ubuntu-slim

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: build
        run: npm install

      - name: test
        run: npm test

      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
            package*

      - name: deploy
        run: echo "my code is deployed"
